"""add timestamps to student table

Revision ID: 0dba166f73d8
Revises: 0ac6e518f300
Create Date: 2026-07-14 18:06:54.366309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dba166f73d8'
down_revision: Union[str, Sequence[str], None] = '0ac6e518f300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('students_parent_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'parents', ['parent_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_parent_id_fkey'), 'students', 'parents', ['parent_id'], ['id'])
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    # ### end Alembic commands ###
