"""add missing route_id to students

Revision ID: 29141757c63c
Revises: 8e937b165db3
Create Date: 2026-07-24 00:46:42.848822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29141757c63c'
down_revision: Union[str, Sequence[str], None] = '8e937b165db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buses', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('buses', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'buses', ['bus_number'])
    op.drop_constraint(op.f('buses_driver_id_fkey'), 'buses', type_='foreignkey')
    op.create_foreign_key(None, 'buses', 'routes', ['route_id'], ['id'])
    op.create_foreign_key(None, 'buses', 'drivers', ['driver_id'], ['id'])
    op.drop_constraint(op.f('routes_bus_id_fkey'), 'routes', type_='foreignkey')
    op.drop_column('routes', 'bus_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('bus_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('routes_bus_id_fkey'), 'routes', 'buses', ['bus_id'], ['id'])
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.create_foreign_key(op.f('buses_driver_id_fkey'), 'buses', 'drivers', ['driver_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'buses', type_='unique')
    op.alter_column('buses', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('buses', 'registration_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
