"""create bus table

Revision ID: 755da2663971
Revises: 0dba166f73d8
Create Date: 2026-07-16 12:43:15.225416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755da2663971'
down_revision: Union[str, Sequence[str], None] = '0dba166f73d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('buses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('buses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('buses', 'bus_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('buses', 'registration_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('buses', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('buses_route_id_fkey'), 'buses', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('buses_route_id_fkey'), 'buses', 'routes', ['route_id'], ['id'])
    op.alter_column('buses', 'route_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('buses', 'registration_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('buses', 'bus_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('buses', 'updated_at')
    op.drop_column('buses', 'created_at')
    op.drop_column('buses', 'status')
    # ### end Alembic commands ###
