"""add route management

Revision ID: 9f968afd3d51
Revises: d15437bb14aa
Create Date: 2026-07-19 11:17:59.257584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f968afd3d51'
down_revision: Union[str, Sequence[str], None] = 'd15437bb14aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('route_number', sa.String(length=50), nullable=False))
    op.add_column('routes', sa.Column('start_point', sa.String(length=255), nullable=False))
    op.add_column('routes', sa.Column('end_point', sa.String(length=255), nullable=False))
    op.add_column('routes', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('routes', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('routes', sa.Column('bus_id', sa.Integer(), nullable=True))
    op.add_column('routes', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('routes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('routes_route_name_key'), 'routes', type_='unique')
    op.create_unique_constraint(None, 'routes', ['route_number'])
    op.create_foreign_key(None, 'routes', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'routes', 'buses', ['bus_id'], ['id'])
    op.drop_column('routes', 'destination')
    op.drop_column('routes', 'source')
    op.drop_column('routes', 'distance_km')
    op.add_column('students', sa.Column('route_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'route_id')
    op.add_column('routes', sa.Column('distance_km', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('routes', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('routes', sa.Column('destination', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_constraint(None, 'routes', type_='unique')
    op.create_unique_constraint(op.f('routes_route_name_key'), 'routes', ['route_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'created_at')
    op.drop_column('routes', 'driver_id')
    op.drop_column('routes', 'bus_id')
    op.drop_column('routes', 'status')
    op.drop_column('routes', 'estimated_duration')
    op.drop_column('routes', 'end_point')
    op.drop_column('routes', 'start_point')
    op.drop_column('routes', 'route_number')
    # ### end Alembic commands ###
