"""add fk constraint bus.route_id to routes

Revision ID: a8184dcae877
Revises: 30f4f1f1fd39
Create Date: 2026-07-16 15:21:27.858598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8184dcae877'
down_revision: Union[str, Sequence[str], None] = '30f4f1f1fd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'buses', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buses', type_='foreignkey')
    # ### end Alembic commands ###
