"""add license_expiry, status, timestamps to drivers

Revision ID: d15437bb14aa
Revises: a8184dcae877
Create Date: 2026-07-18 17:57:48.825521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15437bb14aa'
down_revision: Union[str, Sequence[str], None] = 'a8184dcae877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('license_expiry', sa.Date(), nullable=True))
    op.add_column('drivers', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('drivers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('drivers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'updated_at')
    op.drop_column('drivers', 'created_at')
    op.drop_column('drivers', 'status')
    op.drop_column('drivers', 'license_expiry')
    # ### end Alembic commands ###
