"""create buses table

Revision ID: d6291f0d2ddb
Revises: a8184dcae877
Create Date: 2026-07-20 18:39:45.388622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6291f0d2ddb'
down_revision: Union[str, Sequence[str], None] = 'a8184dcae877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buses', 'registration_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('buses', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('buses_bus_number_key'), 'buses', type_='unique')
    op.drop_constraint(op.f('buses_route_id_fkey'), 'buses', type_='foreignkey')
    op.drop_constraint(op.f('buses_driver_id_fkey'), 'buses', type_='foreignkey')
    op.create_foreign_key(None, 'buses', 'drivers', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.create_foreign_key(op.f('buses_driver_id_fkey'), 'buses', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(op.f('buses_route_id_fkey'), 'buses', 'routes', ['route_id'], ['id'])
    op.create_unique_constraint(op.f('buses_bus_number_key'), 'buses', ['bus_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('buses', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('buses', 'registration_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###